apiVersion: v1
kind: Service
metadata:
  name: shopify-backend
  labels:
    app: bookshelf
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: bookshelf
    tier: backend
