steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:latest', '-t', 'us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:latest', '-t', 'us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:$COMMIT_SHA', '.' ]
images:
- 'us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:latest'
- 'us.gcr.io/shopify-winter-2019/gke_shopify_winter_2019:$COMMIT_SHA'
timeout: 3600s