version: '3'
services:
  db:
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data:Z
  web:
    build: .
    command: ["rails","server","-b","0.0.0.0","-p","3000"]
    volumes:
      - .:/www
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres-data-volume:
    external: true
