apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: '${EMAIL}'
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: staging-clouddns
        clouddns:
          serviceAccountSecretRef:
            name: dns-svc-acct-secret
            key: credentials.json
          project: ${PROJECT_ID}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: '${EMAIL}'
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
      - name: prod-clouddns
        clouddns:
          serviceAccountSecretRef:
            name: dns-svc-acct-secret
            key: credentials.json
          project: ${PROJECT_ID}
