default: &default
  project_id: william-harvey-shopify-2019
  gcs_bucket: william-harvey-shopify-bucket
  #pubsub_topic: [YOUR_PUBSUB_TOPIC]
  #pubsub_subscription: [YOUR_PUBSUB_SUBSCRIPTION]
  #oauth2:
  #  client_id: [YOUR_CLIENT_ID]
  #  client_secret: [YOUR_CLIENT_SECRET]

development:
  <<: *default

production:
  <<: *default
